[package]
name = "crab-cryptor"
version = "1.0.0"
edition = "2021"
authors = ["xl_g <lr_kkr@outlook.com>"]
description = "A simple file cryptor"
repository = "https://github.com/lrkkr/crab-cryptor"
readme = "README.md"
keywords = ["cli", "encrypt", "decrypt"]
categories = ["cryptography", "command-line-utilities", "filesystem"]
license = "MIT"

[dependencies]
anyhow = "1.0.66"
base64 = "0.21"
chacha20poly1305 = { version = "0.10.1", features = ["stream"] }
clap = { version = "4.0.29", features = ["derive"] }
indicatif = "0.17.2"
regex = "1.7.0"
ring = "0.17.7"
walkdir = "2.3.2"

[[bin]]
name = "crab"
path = "src/main.rs"
